// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06.10.2024 00:24:26
const configMerger = require("C:/Dev/Github/NasaSP24/src/Frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Dev/Github/NasaSP24/src/Frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/src/Frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/src/Frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/src/Frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/src/Frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/src/Frontend/plugins/**/*.{js,ts,mjs}","C:/Dev/Github/NasaSP24/src/Frontend/composables/**/*.{js,ts,mjs}","C:/Dev/Github/NasaSP24/src/Frontend/utils/**/*.{js,ts,mjs}","C:/Dev/Github/NasaSP24/src/Frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/src/Frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/src/Frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
