// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 05.10.2024 14:00:56
const configMerger = require("C:/Dev/Github/NasaSP24/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Dev/Github/NasaSP24/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/plugins/**/*.{js,ts,mjs}","C:/Dev/Github/NasaSP24/composables/**/*.{js,ts,mjs}","C:/Dev/Github/NasaSP24/utils/**/*.{js,ts,mjs}","C:/Dev/Github/NasaSP24/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Dev/Github/NasaSP24/app.config.{js,ts,mjs}"] }));

module.exports = config
